import HeroSection from '../components/sections/HeroSection.jsx';
import ComponentCard from '../components/sections/ComponentCard.jsx';
import { useComponents } from '../hooks/useComponents.js';
import { Link } from 'react-router-dom';
import Button from '../components/ui/Button.jsx';
import Spinner from '../components/ui/Spinner.jsx';

export default function HomePage() {
  const { components, loading } = useComponents({ limit: 8 });

  const s = {
    section: { padding: '3rem 1.5rem', maxWidth: 1100, margin: '0 auto' },
    header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' },
    h2: { fontSize: '1.3rem', fontWeight: 800 },
    grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: '1rem' },
    themeBanner: {
      margin: '0 1.5rem 3rem', borderRadius: 'var(--radius-lg)',
      background: 'linear-gradient(135deg, rgba(108,99,255,0.15), rgba(0,217,163,0.08))',
      border: '1px solid rgba(108,99,255,0.3)', padding: '2.5rem',
      textAlign: 'center',
    },
  };

  return (
    <div>
      <HeroSection />
      <div style={s.section}>
        <div style={s.header}>
          <h2 style={s.h2}>Popular Components</h2>
          <Link to="/components"><Button variant="ghost" size="sm">View All →</Button></Link>
        </div>
        {loading
          ? <div style={{ display: 'flex', justifyContent: 'center', padding: '3rem' }}><Spinner size={36} /></div>
          : <div style={s.grid}>{components.slice(0, 8).map(c => <ComponentCard key={c._id} component={c} />)}</div>
        }
      </div>
      <div style={s.themeBanner}>
        <div style={{ fontSize: '2rem', marginBottom: '0.6rem' }}>🎨</div>
        <h2 style={{ fontSize: '1.5rem', fontWeight: 800, marginBottom: '0.5rem' }}>AI Theme Generator</h2>
        <p style={{ color: 'var(--color-text-muted)', marginBottom: '1.5rem', maxWidth: 480, margin: '0 auto 1.5rem' }}>
          Answer 3 quick questions → get a complete color palette, font pairing, and CSS variables generated by AI.
        </p>
        <Link to="/theme"><Button size="lg">Generate My Theme ✦</Button></Link>
      </div>
    </div>
  );
}
